name: Save Data

on:
  workflow_dispatch:
    inputs:
      data:
        description: 'JSON data to save'
        required: true
        type: string

jobs:
  save-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Save data to teams.json
        run: |
          echo '${{ github.event.inputs.data }}' > teams.json
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add teams.json
          git commit -m "Update teams data"
          git push
